// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package transactions

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// User payment and wallet transactions
type Transaction struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	// Amount in smallest currency unit (e.g. kobo for NGN)
	Amount   int64  `json:"amount"`
	Currency string `json:"currency"`
	Status   string `json:"status"`
	Type     string `json:"type"`
	// Unique external or internal payment reference
	Reference   string  `json:"reference"`
	Description *string `json:"description"`
	Provider    *string `json:"provider"`
	// Optional provider-specific payload
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
