// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package transactions

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeleteTransaction(ctx context.Context, id pgtype.UUID) error
	GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error)
	GetTransactionByReference(ctx context.Context, reference string) (Transaction, error)
	ListTransactionsByUserID(ctx context.Context, arg ListTransactionsByUserIDParams) ([]Transaction, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
