// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package verification

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Verification struct {
	ID pgtype.UUID `json:"id"`
	// this stroes the generated code for the email or phone number verification
	Code string `json:"code"`
	// the type of verification e.g 'email' or 'phone_number'
	Type string `json:"type"`
	// the verification identifier can be either the email address or phone number
	Identifier string `json:"identifier"`
	// this indicates when the given token is expiring
	ExpiredAt time.Time `json:"expired_at"`
	// verification created date
	CreatedAt time.Time `json:"created_at"`
}
