// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package verification

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error)
	DeleteExpiredVerifications(ctx context.Context) error
	DeleteVerification(ctx context.Context, id pgtype.UUID) error
	DeleteVerificationByIdentifierAndType(ctx context.Context, arg DeleteVerificationByIdentifierAndTypeParams) error
	GetValidVerification(ctx context.Context, arg GetValidVerificationParams) (Verification, error)
	GetVerificationByID(ctx context.Context, id pgtype.UUID) (Verification, error)
	ListVerificationsByIdentifier(ctx context.Context, identifier string) ([]Verification, error)
}

var _ Querier = (*Queries)(nil)
