// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification.sql

package verification

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerification = `-- name: CreateVerification :one
INSERT INTO verification (
  code,
  type,
  identifier,
  expired_at
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, code, type, identifier, expired_at, created_at
`

type CreateVerificationParams struct {
	Code       string    `json:"code"`
	Type       string    `json:"type"`
	Identifier string    `json:"identifier"`
	ExpiredAt  time.Time `json:"expired_at"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, createVerification,
		arg.Code,
		arg.Type,
		arg.Identifier,
		arg.ExpiredAt,
	)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Identifier,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredVerifications = `-- name: DeleteExpiredVerifications :exec
DELETE FROM verification
WHERE expired_at <= now()
`

func (q *Queries) DeleteExpiredVerifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredVerifications)
	return err
}

const deleteVerification = `-- name: DeleteVerification :exec
DELETE FROM verification
WHERE id = $1
`

func (q *Queries) DeleteVerification(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerification, id)
	return err
}

const deleteVerificationByIdentifierAndType = `-- name: DeleteVerificationByIdentifierAndType :exec
DELETE FROM verification
WHERE identifier = $1
  AND type = $2
`

type DeleteVerificationByIdentifierAndTypeParams struct {
	Identifier string `json:"identifier"`
	Type       string `json:"type"`
}

func (q *Queries) DeleteVerificationByIdentifierAndType(ctx context.Context, arg DeleteVerificationByIdentifierAndTypeParams) error {
	_, err := q.db.Exec(ctx, deleteVerificationByIdentifierAndType, arg.Identifier, arg.Type)
	return err
}

const getValidVerification = `-- name: GetValidVerification :one
SELECT id, code, type, identifier, expired_at, created_at
FROM verification
WHERE
  code = $1
  AND type = $2
  AND identifier = $3
  AND expired_at > now()
LIMIT 1
`

type GetValidVerificationParams struct {
	Code       string `json:"code"`
	Type       string `json:"type"`
	Identifier string `json:"identifier"`
}

func (q *Queries) GetValidVerification(ctx context.Context, arg GetValidVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, getValidVerification, arg.Code, arg.Type, arg.Identifier)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Identifier,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationByID = `-- name: GetVerificationByID :one
SELECT id, code, type, identifier, expired_at, created_at
FROM verification
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetVerificationByID(ctx context.Context, id pgtype.UUID) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerificationByID, id)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Identifier,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listVerificationsByIdentifier = `-- name: ListVerificationsByIdentifier :many
SELECT id, code, type, identifier, expired_at, created_at
FROM verification
WHERE identifier = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVerificationsByIdentifier(ctx context.Context, identifier string) ([]Verification, error) {
	rows, err := q.db.Query(ctx, listVerificationsByIdentifier, identifier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Verification{}
	for rows.Next() {
		var i Verification
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Type,
			&i.Identifier,
			&i.ExpiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
