// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/michaelassa01/gomacbot/db/models (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination db/mock/store.go github.com/michaelassa01/gomacbot/db/models Store
//

// Package mock_db is a generated GoMock package.
package mock_db
